Fixes ambiguous overload 'to_string(int)' for gcc-4.4
Calling std::string(int) with GCC 4.4 resulted in:
test-yaspgrid.cc: In function ‘void check_yasp() [with int dim = 1, CC = Dune::EquidistantCoordinateContainer<double, 1>]’:
test-yaspgrid.cc:117:   instantiated from here
test-yaspgrid.cc:105: error: call of overloaded ‘to_string(int)’ is ambiguous
/usr/include/c++/4.4/bits/basic_string.h:2604: note: candidates are: std::string std::to_string(long long int)
/usr/include/c++/4.4/bits/basic_string.h:2610: note:                 std::string std::to_string(long long unsigned int)
/usr/include/c++/4.4/bits/basic_string.h:2616: note:                 std::string std::to_string(long double)

This patch fixes this by constructing the string using ostrstream instead of
"bla blub"+std::string(int).