[BugFix] Make test compile with gcc-4.4
Somehow the compiler fails to see the type EntityPointer
in YaspGrid<2>::LeafGridView::template Codim<0>::Iterator
due to nesting the lookup through typdefs.
Using the above type directly it complains about missing
conversions e.g.:
persistentcontainertest.cc:73:100: error: conversion from ‘Dune::Entity<0, 2, const Dune::YaspGrid<2>, Dune::YaspEntity>::EntityPointer {aka Dune::EntityPointer<const Dune::YaspGrid<2>, Dune::YaspEntityPointer<0, const Dune::YaspGrid<2> > >}’ to non-scalar type ‘Dune::EntityPointer<const Dune::YaspGrid<2>, Dune::YaspLevelIterator<0, (Dune::PartitionIteratorType)4u, const Dune::YaspGrid<2> > >’ requested
persistentcontainertest.cc: In instantiation of ‘bool test(GridType&) [with GridType = Dune::ALUCubeGrid<2, 2>]’:

As the types are clearly distinct, I consider this a fix.


[[Imported from SVN: r8783]]